export enum InstituteType {
  DHAMMA_SCHOOL = 'dhamma_school',
  SCHOOL = 'school',
  PRIMARY_SCHOOL = 'primary_school',
  SECONDARY_SCHOOL = 'secondary_school',
  TUITION_INSTITUTE = 'tuition_institute',
  ONLINE_ACADEMY = 'online_academy',
  PRE_SCHOOL = 'pre_school',
  OTHER = 'other',
}

export enum InstituteStatus {
  PENDING = 'pending',
  APPROVED = 'approved',
  REJECTED = 'rejected',
  SUSPENDED = 'suspended',
  UNDER_REVIEW = 'under_review',
  CLOSED = 'closed',
}

export enum Country {
  SRI_LANKA = "Sri Lanka"
}

export enum District {
  COLOMBO = "COLOMBO",
  GAMPAHA = "GAMPAHA",
  KALUTARA = "KALUTARA",
  KANDY = "KANDY",
  MATALE = "MATALE",
  NUWARA_ELIYA = "NUWARA_ELIYA",
  GALLE = "GALLE",
  MATARA = "MATARA",
  HAMBANTOTA = "HAMBANTOTA",
  JAFFNA = "JAFFNA",
  KILINOCHCHI = "KILINOCHCHI",
  MANNAR = "MANNAR",
  MULLAITIVU = "MULLAITIVU",
  VAVUNIYA = "VAVUNIYA",
  TRINCOMALEE = "TRINCOMALEE",
  BATTICALOA = "BATTICALOA",
  AMPARA = "AMPARA",
  KURUNEGALA = "KURUNEGALA",
  PUTTALAM = "PUTTALAM",
  ANURADHAPURA = "ANURADHAPURA",
  POLONNARUWA = "POLONNARUWA",
  BADULLA = "BADULLA",
  MONARAGALA = "MONARAGALA",
  RATNAPURA = "RATNAPURA",
  KEGALLE = "KEGALLE",
}

export enum Province {
  WESTERN = "WESTERN",
  CENTRAL = "CENTRAL",
  SOUTHERN = "SOUTHERN",
  NORTHERN = "NORTHERN",
  EASTERN = "EASTERN",
  NORTH_WESTERN = "NORTH_WESTERN",
  NORTH_CENTRAL = "NORTH_CENTRAL",
  UVA = "UVA",
  SABARAGAMUWA = "SABARAGAMUWA",
}

export enum SubjectType {
  MAIN = "MAIN",
  OPTIONAL = "OPTIONAL",
  EXTRA = "EXTRA",
}

export enum BasketCategory {
  COMMON = "COMMON",
  G001 = "G001",
  G002 = "G002",
  G003 = "G003",
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum SubscriptionPlan {
  FREE = 'FREE',
  WHATSAPP = 'WHATSAPP',
  TELEGRAM = 'TELEGRAM',
  EMAIL = 'EMAIL',
  PRO_WHATSAPP = 'PRO-WHATSAPP',
  PRO_SMS = 'PRO-SMS',
  PRO_TELEGRAM = 'PRO-TELEGRAM',
  PRO_EMAIL = 'PRO-EMAIL',
  DYNAMAD = 'DYNAMAD',
}

export enum SMSVerificationAction {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
}

export enum MediaType {
  IMAGE = 'image',
  VIDEO = 'video',
  AUDIO = 'audio',
  PDF = 'pdf',
}

export enum SupportivePlatform {
  SMS = 'sms',
  WHATSAPP = 'whatsapp',
  TELEGRAM = 'telegram',
  EMAIL = 'email',
  MOBILE_PUSH = 'mobile-push',
  WEB_PUSH = 'web-push',
}

export enum UserType {
  SUPERADMIN = 'SUPER_ADMIN',
  ORGANIZATION_MANAGER = 'ORGANIZATION_MANAGER',
  USER = 'USER',
  USER_WITHOUT_PARENT = 'USER_WITHOUT_PARENT',
  USER_WITHOUT_STUDENT = 'USER_WITHOUT_STUDENT',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum InstituteUserType {
  INSTITUTE_ADMIN = 'INSTITUTE_ADMIN',
  TEACHER = 'TEACHER',
  STUDENT = 'STUDENT',
  ATTENDANCE_MARKER = 'ATTENDANCE_MARKER',
  PARENT = 'PARENT',
}

export enum Occupation {
  TEACHER = 'TEACHER',
  LECTURER = 'LECTURER',
  PRINCIPAL = 'PRINCIPAL',
  TUITION_TEACHER = 'TUITION_TEACHER',
  SCHOOL_COUNSELOR = 'SCHOOL_COUNSELOR',
  TUITION_INSTITUTE_OWNER = 'TUITION_INSTITUTE_OWNER',
  LIBRARIAN = 'LIBRARIAN',
  NURSE = 'NURSE',
  DOCTOR = 'DOCTOR',
  PHARMACIST = 'PHARMACIST',
  LABORATORY_TECHNICIAN = 'LABORATORY_TECHNICIAN',
  MIDWIFE = 'MIDWIFE',
  DENTIST = 'DENTIST',
  VETERINARY_DOCTOR = 'VETERINARY_DOCTOR',
  ENGINEER = 'ENGINEER',
  CIVIL_ENGINEER = 'CIVIL_ENGINEER',
  ARCHITECT = 'ARCHITECT',
  QUANTITY_SURVEYOR = 'QUANTITY_SURVEYOR',
  TECHNICIAN = 'TECHNICIAN',
  IT_OFFICER = 'IT_OFFICER',
  SOFTWARE_DEVELOPER = 'SOFTWARE_DEVELOPER',
  WEB_DEVELOPER = 'WEB_DEVELOPER',
  GRAPHIC_DESIGNER = 'GRAPHIC_DESIGNER',
  ACCOUNTANT = 'ACCOUNTANT',
  BANK_OFFICER = 'BANK_OFFICER',
  INSURANCE_AGENT = 'INSURANCE_AGENT',
  MARKETING_EXECUTIVE = 'MARKETING_EXECUTIVE',
  ENTREPRENEUR = 'ENTREPRENEUR',
  BUSINESS_OWNER = 'BUSINESS_OWNER',
  SHOP_OWNER = 'SHOP_OWNER',
  MANAGER = 'MANAGER',
  SUPERVISOR = 'SUPERVISOR',
  CLERK = 'CLERK',
  CASHIER = 'CASHIER',
  RECEPTIONIST = 'RECEPTIONIST',
  SALES_EXECUTIVE = 'SALES_EXECUTIVE',
  DRIVER = 'DRIVER',
  BUS_DRIVER = 'BUS_DRIVER',
  DELIVERY_RIDER = 'DELIVERY_RIDER',
  FARMER = 'FARMER',
  FISHERMAN = 'FISHERMAN',
  POLICE_OFFICER = 'POLICE_OFFICER',
  SOLDIER = 'SOLDIER',
  SECURITY_GUARD = 'SECURITY_GUARD',
  MECHANIC = 'MECHANIC',
  ELECTRICIAN = 'ELECTRICIAN',
  PLUMBER = 'PLUMBER',
  CARPENTER = 'CARPENTER',
  MASON = 'MASON',
  WELDER = 'WELDER',
  TAILOR = 'TAILOR',
  HAIRDRESSER = 'HAIRDRESSER',
  BEAUTICIAN = 'BEAUTICIAN',
  CHEF = 'CHEF',
  COOK = 'COOK',
  WAITER = 'WAITER',
  HOTEL_STAFF = 'HOTEL_STAFF',
  ARTIST = 'ARTIST',
  MUSICIAN = 'MUSICIAN',
  PHOTOGRAPHER = 'PHOTOGRAPHER',
  GYM_INSTRUCTOR = 'GYM_INSTRUCTOR',
  HOUSEWIFE = 'HOUSEWIFE',
  DOMESTIC_WORKER = 'DOMESTIC_WORKER',
  FACTORY_WORKER = 'FACTORY_WORKER',
  LABOURER = 'LABOURER',
  CIVIL_SERVANT = 'CIVIL_SERVANT',
  GOVERNMENT_OFFICER = 'GOVERNMENT_OFFICER',
  LAWYER = 'LAWYER',
  RESEARCHER = 'RESEARCHER',
  SOCIAL_WORKER = 'SOCIAL_WORKER',
  JOURNALIST = 'JOURNALIST',
  STUDENT_SCHOOL = 'STUDENT_SCHOOL',
  STUDENT_UNIVERSITY = 'STUDENT_UNIVERSITY',
  RETIRED_PERSON = 'RETIRED_PERSON',
  UNEMPLOYED = 'UNEMPLOYED',
  OTHER = 'OTHER',
}

// Card Management Enums
export enum CardType {
  NFC = 'NFC',
  PVC = 'PVC',
  TEMPORARY = 'TEMPORARY',
}

export enum CardStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DEACTIVATED = 'DEACTIVATED',
  EXPIRED = 'EXPIRED',
  LOST = 'LOST',
  DAMAGED = 'DAMAGED',
  REPLACED = 'REPLACED',
}

export enum OrderStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  VERIFYING = 'VERIFYING',
  VERIFIED = 'VERIFIED',
  PREPARING = 'PREPARING',
  PRINTING = 'PRINTING',
  DELIVERING = 'DELIVERING',
  ON_THE_WAY = 'ON_THE_WAY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
}

export enum CardPaymentType {
  SLIP_UPLOAD = 'SLIP_UPLOAD',
  VISA_MASTER = 'VISA_MASTER',
}

export enum CardPaymentStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}
