export enum Occupation {
  // Education & Training
  TEACHER = 'TEACHER',
  LECTURER = 'LECTURER',
  PRINCIPAL = 'PRINCIPAL',
  TUITION_TEACHER = 'TUITION_TEACHER',
  SCHOOL_COUNSELOR = 'SCHOOL_COUNSELOR',
  TUITION_INSTITUTE_OWNER = 'TUITION_INSTITUTE_OWNER',
  LIBRARIAN = 'LIBRARIAN',

  // Healthcare & Medical
  NURSE = 'NURSE',
  DOCTOR = 'DOCTOR',
  PHARMACIST = 'PHARMACIST',
  LABORATORY_TECHNICIAN = 'LABORATORY_TECHNICIAN',
  MIDWIFE = 'MIDWIFE',
  DENTIST = 'DENTIST',
  VETERINARY_DOCTOR = 'VETERINARY_DOCTOR',
  PHARMACIST_ASSISTANT = 'PHARMACIST_ASSISTANT',
  MEDICAL_REPRESENTATIVE = 'MEDICAL_REPRESENTATIVE',

  // Engineering & Technical
  ENGINEER = 'ENGINEER',
  CIVIL_ENGINEER = 'CIVIL_ENGINEER',
  ARCHITECT = 'ARCHITECT',
  QUANTITY_SURVEYOR = 'QUANTITY_SURVEYOR',
  SURVEYOR = 'SURVEYOR',
  DRAFTSMAN = 'DRAFTSMAN',
  TECHNICIAN = 'TECHNICIAN',
  AIR_CONDITIONING_TECHNICIAN = 'AIR_CONDITIONING_TECHNICIAN',
  AUTO_ELECTRICIAN = 'AUTO_ELECTRICIAN',
  MOBILE_TECHNICIAN = 'MOBILE_TECHNICIAN',
  COMPUTER_TECHNICIAN = 'COMPUTER_TECHNICIAN',
  CCTV_INSTALLER = 'CCTV_INSTALLER',

  // IT & Technology
  IT_OFFICER = 'IT_OFFICER',
  SOFTWARE_DEVELOPER = 'SOFTWARE_DEVELOPER',
  WEB_DEVELOPER = 'WEB_DEVELOPER',
  GRAPHIC_DESIGNER = 'GRAPHIC_DESIGNER',
  CONTENT_CREATOR = 'CONTENT_CREATOR',
  YOUTUBER = 'YOUTUBER',
  DATA_ENTRY_OPERATOR = 'DATA_ENTRY_OPERATOR',
  SOCIAL_MEDIA_MARKETER = 'SOCIAL_MEDIA_MARKETER',

  // Business & Finance
  ACCOUNTANT = 'ACCOUNTANT',
  BANK_OFFICER = 'BANK_OFFICER',
  INSURANCE_AGENT = 'INSURANCE_AGENT',
  MARKETING_EXECUTIVE = 'MARKETING_EXECUTIVE',
  ENTREPRENEUR = 'ENTREPRENEUR',
  BUSINESS_OWNER = 'BUSINESS_OWNER',
  SHOP_OWNER = 'SHOP_OWNER',
  BOUTIQUE_OWNER = 'BOUTIQUE_OWNER',
  GROCERY_SHOP_OWNER = 'GROCERY_SHOP_OWNER',
  TAILORING_SHOP_OWNER = 'TAILORING_SHOP_OWNER',
  BEAUTY_SALON_OWNER = 'BEAUTY_SALON_OWNER',
  BARBER_SHOP_OWNER = 'BARBER_SHOP_OWNER',
  CONSULTANT = 'CONSULTANT',
  MANAGER = 'MANAGER',
  SUPERVISOR = 'SUPERVISOR',
  HR_OFFICER = 'HR_OFFICER',
  HR_EXECUTIVE = 'HR_EXECUTIVE',
  PROCUREMENT_OFFICER = 'PROCUREMENT_OFFICER',

  // Administrative & Clerical
  CLERK = 'CLERK',
  CASHIER = 'CASHIER',
  RECEPTIONIST = 'RECEPTIONIST',
  CASH_COLLECTOR = 'CASH_COLLECTOR',
  STORE_KEEPER = 'STORE_KEEPER',
  STORE_MANAGER = 'STORE_MANAGER',
  WAREHOUSE_ASSISTANT = 'WAREHOUSE_ASSISTANT',

  // Sales & Customer Service
  SALES_EXECUTIVE = 'SALES_EXECUTIVE',
  SALESMAN = 'SALESMAN',
  SHOP_ASSISTANT = 'SHOP_ASSISTANT',
  CALL_CENTER_AGENT = 'CALL_CENTER_AGENT',
  CALL_CENTER_SUPERVISOR = 'CALL_CENTER_SUPERVISOR',

  // Transportation & Logistics
  DRIVER = 'DRIVER',
  BUS_DRIVER = 'BUS_DRIVER',
  TUK_TUK_DRIVER = 'TUK_TUK_DRIVER',
  TAXI_DRIVER = 'TAXI_DRIVER',
  HEAVY_VEHICLE_DRIVER = 'HEAVY_VEHICLE_DRIVER',
  DELIVERY_RIDER = 'DELIVERY_RIDER',
  DELIVERY_PARTNER = 'DELIVERY_PARTNER',
  DELIVERY_HELPER = 'DELIVERY_HELPER',
  DELIVERY_DISPATCHER = 'DELIVERY_DISPATCHER',
  BUS_CONDUCTOR = 'BUS_CONDUCTOR',
  DRIVER_ASSISTANT = 'DRIVER_ASSISTANT',
  CRANE_OPERATOR = 'CRANE_OPERATOR',
  FORKLIFT_OPERATOR = 'FORKLIFT_OPERATOR',
  BUS_OWNER = 'BUS_OWNER',
  VEHICLE_INSPECTOR = 'VEHICLE_INSPECTOR',
  BOATMAN = 'BOATMAN',
  FERRY_OPERATOR = 'FERRY_OPERATOR',

  // Agriculture & Farming
  FARMER = 'FARMER',
  TEA_ESTATE_WORKER = 'TEA_ESTATE_WORKER',
  RUBBER_TAPPER = 'RUBBER_TAPPER',
  COCONUT_FARMER = 'COCONUT_FARMER',
  PADDY_FARMER = 'PADDY_FARMER',
  SPICE_CULTIVATOR = 'SPICE_CULTIVATOR',
  VEGETABLE_CULTIVATOR = 'VEGETABLE_CULTIVATOR',
  POULTRY_FARMER = 'POULTRY_FARMER',
  LIVESTOCK_FARMER = 'LIVESTOCK_FARMER',
  DAIRY_FARMER = 'DAIRY_FARMER',

  // Fishing & Marine
  FISHERMAN = 'FISHERMAN',
  FISHER = 'FISHER',
  NET_REPAIRER = 'NET_REPAIRER',
  FISH_SELLER = 'FISH_SELLER',

  // Security & Defense
  POLICE_OFFICER = 'POLICE_OFFICER',
  SOLDIER = 'SOLDIER',
  NAVY = 'NAVY',
  AIR_FORCE = 'AIR_FORCE',
  SECURITY_GUARD = 'SECURITY_GUARD',
  SECURITY_SUPERVISOR = 'SECURITY_SUPERVISOR',
  WATCHMAN = 'WATCHMAN',

  // Construction & Skilled Trades
  MECHANIC = 'MECHANIC',
  BUS_MECHANIC = 'BUS_MECHANIC',
  LIGHT_VEHICLE_MECHANIC = 'LIGHT_VEHICLE_MECHANIC',
  ELECTRICIAN = 'ELECTRICIAN',
  PLUMBER = 'PLUMBER',
  CARPENTER = 'CARPENTER',
  MASON = 'MASON',
  WELDER = 'WELDER',
  PAINTER_BUILDING = 'PAINTER_BUILDING',
  PAINTER_VEHICLE = 'PAINTER_VEHICLE',
  CONSTRUCTION_WORKER = 'CONSTRUCTION_WORKER',

  // Fashion & Beauty
  TAILOR = 'TAILOR',
  DRESSMAKER = 'DRESSMAKER',
  FASHION_DESIGNER = 'FASHION_DESIGNER',
  TAILORING_ASSISTANT = 'TAILORING_ASSISTANT',
  HAIRDRESSER = 'HAIRDRESSER',
  BEAUTICIAN = 'BEAUTICIAN',
  BARBER = 'BARBER',

  // Food & Hospitality
  CHEF = 'CHEF',
  COOK = 'COOK',
  BAKER = 'BAKER',
  PASTRY_CHEF = 'PASTRY_CHEF',
  WAITER = 'WAITER',
  WAITRESS = 'WAITRESS',
  HOTEL_STAFF = 'HOTEL_STAFF',
  TOUR_GUIDE = 'TOUR_GUIDE',

  // Arts & Entertainment
  ARTIST = 'ARTIST',
  MUSICIAN = 'MUSICIAN',
  DANCER = 'DANCER',
  PHOTOGRAPHER = 'PHOTOGRAPHER',
  VIDEOGRAPHER = 'VIDEOGRAPHER',
  PHOTOGRAPHER_ASSISTANT = 'PHOTOGRAPHER_ASSISTANT',
  CAMERAMAN = 'CAMERAMAN',
  ACTOR = 'ACTOR',
  ACTRESS = 'ACTRESS',
  SINGER = 'SINGER',
  MUSIC_TEACHER = 'MUSIC_TEACHER',
  PAINTER_ARTIST = 'PAINTER_ARTIST',

  // Fitness & Sports
  GYM_INSTRUCTOR = 'GYM_INSTRUCTOR',
  SPORTS_COACH = 'SPORTS_COACH',
  FITNESS_TRAINER = 'FITNESS_TRAINER',

  // Domestic & Personal Services
  HOUSEWIFE = 'HOUSEWIFE',
  HOUSEMAID = 'HOUSEMAID',
  DOMESTIC_WORKER = 'DOMESTIC_WORKER',
  GARDENER = 'GARDENER',
  CLEANER = 'CLEANER',
  JANITOR = 'JANITOR',

  // Manual Labor & General Work
  FACTORY_WORKER = 'FACTORY_WORKER',
  LABOURER = 'LABOURER',
  FRUIT_SELLER = 'FRUIT_SELLER',
  STREET_VENDOR = 'STREET_VENDOR',
  SMALL_BUSINESS_VENDOR = 'SMALL_BUSINESS_VENDOR',

  // Government & Public Service
  CIVIL_SERVANT = 'CIVIL_SERVANT',
  GOVERNMENT_OFFICER = 'GOVERNMENT_OFFICER',
  GRAMA_NILADHARI = 'GRAMA_NILADHARI',
  POSTMAN = 'POSTMAN',

  // Legal & Professional Services
  LAWYER = 'LAWYER',
  LEGAL_OFFICER = 'LEGAL_OFFICER',

  // Research & Academia
  RESEARCHER = 'RESEARCHER',
  SCIENTIST = 'SCIENTIST',

  // Social & Community Services
  SOCIAL_WORKER = 'SOCIAL_WORKER',
  NGO_WORKER = 'NGO_WORKER',
  NGO_FIELD_OFFICER = 'NGO_FIELD_OFFICER',
  VOLUNTEER_WORKER = 'VOLUNTEER_WORKER',

  // Religious & Spiritual
  PRIEST = 'PRIEST',
  MONK = 'MONK',
  IMAM = 'IMAM',
  RELIGIOUS_LEADER = 'RELIGIOUS_LEADER',

  // Media & Communication
  JOURNALIST = 'JOURNALIST',
  REPORTER = 'REPORTER',

  // Property & Real Estate
  LANDLORD = 'LANDLORD',
  LANDLADY = 'LANDLADY',

  // Student & Employment Status
  STUDENT_SCHOOL = 'STUDENT_SCHOOL',
  STUDENT_UNIVERSITY = 'STUDENT_UNIVERSITY',
  RETIRED_PERSON = 'RETIRED_PERSON',
  UNEMPLOYED = 'UNEMPLOYED',
}

export const formatOccupation = (occupation: string): string => {
  return occupation
    .split('_')
    .map(word => word.charAt(0) + word.slice(1).toLowerCase())
    .join(' ');
};
