// Temporary fallback types for the Supabase client until autogenerated types are available.
// Do not edit src/integrations/supabase/client.ts. This file satisfies the `import './types'` import.

export type Database = any;
